### ISSUE TITLE
ModuleNotFoundError: No module named 'myeia'

### ISSUE THREAD

**Issue by EPRINC-MP** [philsv/myeia#1]
Greetings, 

I am trying to implement myeia into my scripts. Starting with a test script replicating your instructions, the error message is:
ModuleNotFoundError: No module named 'myeia'

When examining the location of the files, they are placed in:
/usr/local/lib/python3.11/site-packages/src

Changing /usr/local/lib/python3.11/site-packages/src to /usr/local/lib/python3.11/site-packages/myeia, the following error is returned:
from myeia import API
ImportError: cannot import name 'API' from 'myeia' (/usr/local/lib/python3.11/site-packages/myeia/__init__.py)

The file __init__.py is empty. It should contain something like 
from .myeia import API, __version__

No?

Much thanks for your effort and attention. 

Max

p.s. my operating environment is Fedora Linux 37; except for two python modules (entsog and entsoe) installed wity pip, all the rest are installed via dnf/rpm.

**Comment by EPRINC-MP** [comment]
Continuing ...
I've:
moved src to myeia

modified __init__.py to contain:
from .myeia import API, __version__

modified myeia.py like this:
# from pandas.core.common import SettingWithCopyWarning
from pandas.core.generic import SettingWithCopyWarning

__version__ = "0.2.0"

and now the error is:
  File "/usr/local/lib/python3.11/site-packages/myeia/myeia.py", line 54, in get_data
    response.raise_for_status()
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.eia.gov/v2/natural-gas/pri/fut/data/?api_key=None&data%5B%5D=value&frequency=daily&facets%5Bseries%5D%5B%5D=RNGC1&sort%5B0%5D%5Bcolumn%5D=period&sort%5B0%5D%5Bdirection%5D=desc

Somehow, API key isn't being picked up; from the url " ... ?api_key=None ...".

Max

**Comment by philsv** [comment]
I think its fixed now, can you check if it works for you with version 0.2.2?

**Comment by EPRINC-MP** [comment]
Here's the error that I receive:
Traceback (most recent call last):
  File "/home/pyz/projects/Commodities/DataSources/EIA/Development/Electricity/./GetMyEIA.py", line 5, in <module>
    from myeia import API
ImportError: cannot import name 'API' from 'myeia' (/usr/local/lib/python3.11/site-packages/myeia/__init__.py)


__init__.py is empty (size 0). 

I believe that it should have a line something like this:
from .api import API

When I run my script now, it returns the following error:
    df = eia.get_data(
         ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/myeia/api.py", line 48, in get_data
    response.raise_for_status()
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.eia.gov/v2/natural-gas/pri/fut/data/?api_key=None&data%5B%5D=value&frequency=daily&facets%5Bseries%5D%5B%5D=RNGC1&sort%5B0%5D%5Bcolumn%5D=period&sort%5B0%5D%5Bdirection%5D=desc

It fails to pass the API key to the building of the URL. 
Max

**Comment by EPRINC-MP** [comment]
Studying your work, here's my script that for the most part is successful. 

#!/usr/bin/python3

import requests
import pandas as pd

eiaURLData = 'https://api.eia.gov/v2/seriesid/{}?api_key={}'
eiaAuthToken = "<YourEIAAPITokenHere"
eiaSeriesID =  'PET.MD0MP_R10-R20_1.M'
# eiaSeriesID =  'INTL.81-2-ARE-TBPD.A' (For some reason this doesn't work)
url    =  eiaURLData.format(eiaSeriesID, eiaAuthToken)

print(url)

eiaData = requests.get(url)

print(eiaData.status_code)

eiaDataJSON = eiaData.json()

baseEIAData = pd.DataFrame(eiaDataJSON["response"]["data"])
print(baseEIAData.head())

baseEIAColNames = list(baseEIAData)

eiaPrDate = baseEIAColNames[0]
eiaValues = baseEIAColNames[-2]
eiaUnits = baseEIAColNames[-1]
df = baseEIAData[[eiaPrDate, eiaValues]] 

print(df.head())


eiaDelimFile	= "%s.txt" % (eiaSeriesID, )
df.to_csv(eiaDelimFile, sep='\t', header=False, index=False)

**Comment by philsv** [comment]
> from myeia import API

The empty __init__.py already identifies it as a package 
so in that case you would need to do `from myeia.api import API`.

the naming is a bit confusing I understand.


For the series-id: PET.MD0MP_R10-R20_1.M
You would first need to identify the "route" for the new API v2.

I can highly recommend you to use the API dashboard to find all routes first: https://www.eia.gov/opendata/browser/

The route in that case is: "petroleum/move/pipe"
and the series: "MD0MP_R10-R20_1" <- is the series-id from the old apiv1

So your script would start like:

```
from myeia.api import API
eia = API()  # set your API KEY in your .env where the .env.example is located

if __name__ == "__main__":
  df = eia.get_data(route="petroleum/move/pipe", series="MD0MP_R10-R20_1", frequency="monthly", facet="series")
  print(df.head())
  df.to_csv(<your_file_path>)
```

My script is set up in a way that it only returns the value of a given series, so if you want to adjust that to get for example the "units" or "process" you can fork or copy my code and adjust the following part of the api.py file:

```
df = df.iloc[:, :2]
```

I hope this helped!

**Comment by philsv** [comment]
For the series-id: "INTL.81-2-NIC-TBPD.A" 

There seems to be no data available: https://www.eia.gov/opendata/v1/qb.php?sdid=INTL.81-2-NIC-TBPD.A

**Comment by philsv** [comment]
> 



> Here's the error that I receive: Traceback (most recent call last): File "/home/pyz/projects/Commodities/DataSources/EIA/Development/Electricity/./GetMyEIA.py", line 5, in from myeia import API ImportError: cannot import name 'API' from 'myeia' (/usr/local/lib/python3.11/site-packages/myeia/**init**.py)
> 
> **init**.py is empty (size 0).
> 
> I believe that it should have a line something like this: from .api import API
> 
> When I run my script now, it returns the following error: df = eia.get_data( ^^^^^^^^^^^^^ File "/usr/local/lib/python3.11/site-packages/myeia/api.py", line 48, in get_data response.raise_for_status() File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.eia.gov/v2/natural-gas/pri/fut/data/?api_key=None&data%5B%5D=value&frequency=daily&facets%5Bseries%5D%5B%5D=RNGC1&sort%5B0%5D%5Bcolumn%5D=period&sort%5B0%5D%5Bdirection%5D=desc
> 
> It fails to pass the API key to the building of the URL. Max

I tested version 0.2.2 on my WSL 20.04.5 Ubuntu with python 3.10.9 and it should pick up the API KEY from the .env file.

**Comment by EPRINC-MP** [comment]
myeia's design requires three pieces of information:
 - route
 - seriesid
 - frequency.
 
The script that I offered only requires the seriesid. It's a little more efficient; but you need to breakdown EIA's offerings to isolate the seriesid. 

And then hopefully, they won't deprecate the series ids.

**Comment by philsv** [comment]
> This APIv1 method is now deprecated .However, if you are fond of APIv1 Series IDs, you may invoke them using the special /series/ route, as follows. Note that we use a full route, but at the end we include the APIv1 Series_ID:
> 
> https://api.eia.gov/v2/seriesid/ELEC.SALES.CO-RES.A?api_key=xxxxxx

I see they added now the old v1 structure to v2. Yeah that would work fine. 

I might add that to my script soon.
