### ISSUE TITLE
is the API working right now?

### ISSUE THREAD

**Issue by Stevearama** [philsv/myeia#10]
I'm getting 400 errors?  Maybe it's related to the maintenance next week.  Anyone else?

**Comment by philsv** [comment]
Same for me. Most likely yeah service seems to be offline for now. Will check back on it tomorrow.

**Comment by Stevearama** [comment]
Thanks for checking.  Thanks for myeia

**Comment by philsv** [comment]
Tests are still failing for me. But it looks like not for all data, 'INTL.29-12-HKG-BKWH.A' worked for me. I guess they are migrating most of the data right now. Could still be down for couple of days.

**Comment by philsv** [comment]
All tests are working again. Problem should be resolved now. I am closing this issue.
