### ISSUE TITLE
no seriesId

### ISSUE THREAD

**Issue by MikeMike13** [philsv/myeia#16]
Hi, great module! But I have one question and would be happy if you can help)

There are series without seriesId identifier, for example 
https://www.eia.gov/opendata/browser/international?frequency=monthly&data=value;&facets=countryRegionId;&countryRegionId=ARE;&sortColumn=period;&sortDirection=desc;

Let's say I wand to get "Crude oil, NGPL, and other liquids" (2nd page), productId=55.

How can I do it?

Thank you!

Mike

**Comment by philsv** [comment]
I think what you are looking for is the ability to handle multiple facet filters.

```python
df = eia.get_series_via_route(
    route="international",
    series=["ARE", 55],
    frequency="monthly",
    facet=["countryRegionId", "productId"],
)

df.head()
```

Output Example:

```ini
           countryRegionId productId  Crude oil, NGPL, and other liquids
Date                                                                    
2024-03-01             ARE        55                         4132.394334
2024-02-01             ARE        55                         4132.394334
2024-01-01             ARE        55                         4142.394334
2023-12-01             ARE        55                         4082.394334
2023-11-01             ARE        55                         4082.394334
...                    ...       ...                                 ...
```

I have added this functionality to the latest version of myeia `pip install myeia==0.4.1`

**Comment by philsv** [comment]
@MikeMike13 did this resolve your question?

**Comment by MikeMike13** [comment]
> pip install myeia==0.4.1

super cool) yes, it works, thank you!

**Comment by philsv** [comment]
Awesome :) glad it works
