### ISSUE TITLE
start_date

### ISSUE THREAD

**Issue by MikeMike13** [philsv/myeia#18]
Have updated to the latest version, but now it seems start_date is not working properly..)
WLFC = eia.get_series(series_id="STEO.PATC_WORLD.M",start_date="2023-01-01")
WLFC.tail()
data is from 1990...

Thank you!

**Comment by philsv** [comment]
@MikeMike13 could you check if it is working for you again in 0.4.2?

**Comment by MikeMike13** [comment]
> @MikeMike13 could you check if it is working for you again in 0.4.2?

Cool, works great, thank you!

**Comment by philsv** [comment]
awesome 👍
