### ISSUE TITLE
Version 0.2.3 errors

### ISSUE THREAD

**Issue by EPRINC-MP** [philsv/myeia#2]
Encountering errors:
Running ./GetMyEIA.py 
gets
Traceback (most recent call last):
  File "/home/pyz/projects/Commodities/DataSources/EIA/Development/API/./GetMyEIA.py", line 5, in <module>
    from myeia import API
ImportError: cannot import name 'API' from 'myeia' (/usr/local/lib/python3.11/site-packages/myeia/__init__.py)

__init__.py modified to:
from .api import API, __version__

added two lines to api.py 
__title__ = "api.py"
__version__ = "0.2.3"

But, I've put my EIA-API Token in an .env file, but the script still can't find it:
  File "/usr/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
**requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api.eia.gov/v2/seriesid/NG.RNGC1.D?api_key=None**

**Comment by philsv** [comment]
> from myeia import API

The issue is not the __init__.py it is fine being empty. 

You need to import it like so:

```
from myeia.api import API
eia = API()
```

or 

```
from myeia import api
eia = api.API()
```

You are trying to import the class API but you first need to import the script 'api'

Then it should work.

**Comment by EPRINC-MP** [comment]
I have those lines, and the failure to find the token continues. 
See line that is bolded:
**Forbidden for url: https://api.eia.gov/v2/seriesid/NG.RNGC1.D?api_key=None**

**Comment by philsv** [comment]
Where exactly is your .env located and your script?
I had the same issue when for example:
./src/test_myeia.py
./src/.env

but it worked fine with:
./src/test_myeia.py
./.env

If the error persists you could still just do:

`eia = API(token="<your_api_key>")`

without an .env file.

**Comment by EPRINC-MP** [comment]
eia = API(token="<your_api_key>")
works.

and then the output is semi-successful generating the following warnings:

/usr/local/lib/python3.11/site-packages/myeia/api.py:57: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[0]: "Date", df.columns[1]: series_description}, inplace=True)
/usr/local/lib/python3.11/site-packages/myeia/api.py:58: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Date"] = pd.to_datetime(df["Date"])
/usr/local/lib/python3.11/site-packages/myeia/api.py:108: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.rename(columns={df.columns[1]: name}, inplace=True)

**Comment by philsv** [comment]
I created a new version (0.2.4) on pypi with the fix to the /usr/local/lib/python3.11/site-packages/myeia/api.py:57: SettingWithCopyWarning Warning.

**Comment by romanme2** [comment]
Currently having an issue saying:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_15364\1658031437.py in <module>
----> 1 from myeia.api import API
      2 import myeia
      3 eia = API(token='*****')

~\Anaconda3\lib\site-packages\myeia\api.py in <module>
      7 import requests
      8 from dotenv import load_dotenv
----> 9 from pandas.errors import SettingWithCopyWarning
     10 
     11 warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

ImportError: cannot import name 'SettingWithCopyWarning' from 'pandas.errors' (C:\Users\mlr\Anaconda3\lib\site-packages\pandas\errors\__init__.py)

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~\AppData\Local\Temp\ipykernel_16884\1832943710.py in <module>
----> 1 eia.data_by_series_id("PET.RWTC.D")

AttributeError: 'API' object has no attribute 'data_by_series_id'

please advise
