### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by aladakepri** [philsv/myeia#7]
Hi Phil,

Looks like your repo is just about the only up-to-date Python wrapper for the EIA API after the March 2023 change which nullified most projects. I believe getting things by SeriesID is not longer working since v1 was sunset. See: https://github.com/mra1385/EIA-python/issues/9

I could be wrong about this - but I think the docs need to be updated.

**Comment by philsv** [comment]
Hi aladakepri,

I just checked on the single series_id tests and they seem to still work. 
The single_id call is not completely deprecated.
 
https://www.eia.gov/opendata/documentation.php
> This APIv1 method is now deprecated .However, if you are fond of APIv1 Series IDs, 
> you may invoke them using the special /series/ route, as follows. 
> Note that we use a full route, but at the end we include the APIv1 Series_ID:
> 
> https://api.eia.gov/v2/seriesid/ELEC.SALES.CO-RES.A?api_key=xxxxxx
